### ISSUE TITLE
nytimes.com issues [NYT]

### ISSUE THREAD

**Issue by prodan1234** [yourduskquibbles/webannoyances#146]
### URL(s) where the issue occurs

`https://www.nytimes.com/interactive/2019/06/08/technology/youtube-radical.html`

### Describe the issue

With the filter enabled, the page has extra white space and the collage is broken.

### Screenshot(s)

Page with filter enabled (broken):
![alt text](http://giphygifs.s3.amazonaws.com/media/9J8RZGEntVOlQ3lDpz/giphy.gif)

Page without filter enabled:
![alt text](http://giphygifs.s3.amazonaws.com/media/246P9WF2TZD2yBynfF/giphy.gif)

Uploaded [here](https://imgur.com/a/ZgawL6T) as videos.

### Versions

- Browser/version:  Chrome 75.0.3770.90
- uBlock Origin version: 1.20.0

### Settings

Default settings

### Other broken urls

`https://www.nytimes.com/interactive/2018/01/27/technology/social-media-bots.html` 
`https://www.nytimes.com/interactive/2018/05/09/nyregion/subway-crisis-mta-decisions-signals-rules.html` 
`https://www.nytimes.com/interactive/2018/05/30/world/asia/rohingya-monsoon-bangladesh.html` 
`https://www.nytimes.com/interactive/2018/11/07/us/politics/how-democrats-took-the-house.html` 
`https://www.nytimes.com/interactive/2018/12/24/climate/how-electricity-generation-changed-in-your-state.html` 
`https://www.nytimes.com/interactive/2019/05/24/business/media/summer-sequels.html`
`https://www.nytimes.com/interactive/2019/06/12/opinion/facebook-google-privacy-policies.html`

**Comment by yourduskquibbles** [comment]
Thanks for providing all of the test links, will go through and make sure this is fixed.

**Comment by yourduskquibbles** [comment]
@prodan1234 

Please let me know if you are still having issue after purging and updating filters, think I found and have removed the problem filter on the interactive nyt articles.

**Comment by prodan1234** [comment]
@yourduskquibbles Thanks for fixing it. Two of the pages still have issues 
`https://www.nytimes.com/interactive/2018/01/27/technology/social-media-bots.html` 
`https://www.nytimes.com/interactive/2018/05/09/nyregion/subway-crisis-mta-decisions-signals-rules.html`

**Comment by yourduskquibbles** [comment]
@prodan1234 Thanks for testing and reporting back. 

Please try refreshing filters again, I think this is working on all now.

**Comment by yourduskquibbles** [comment]
@prodan1234 Think all reported sites should be working now, please purge filters and retest `https://www.nytimes.com/interactive/2018/05/09/nyregion/subway-crisis-mta-decisions-signals-rules.html` & `https://www.nytimes.com/interactive/2018/01/27/technology/social-media-bots.html`

Thank you for reporting & testing in advance!

**Comment by prodan1234** [comment]
Thanks, all of them work great now.

**Comment by yourduskquibbles** [comment]
@prodan1234 Great, thanks for helping to test the filters!

Please let me know if you find any other broken nytimes.com pages in the future - I've found that fixing their special article pages can be a bit like squeezing a balloon with the changes that happen across different templates so appreciate you finding multiple test links to test with.

**Comment by yourduskquibbles** [comment]
I've added some additional filters to the modal list in commit https://github.com/yourduskquibbles/webannoyances/commit/3793b190f23bf7654bc6087afb172fb288223942 that should allow reading of coronavirus related articles without being forced to login. (This may help on other types of articles but I won't fully know until this madness is over with... and `nytimes.com` is back to their normal site behaviour) From my testing, this should help when not using other extensions such as [`bypass-paywalls-chrome-clean`](https://github.com/magnolia1234/bypass-paywalls-chrome-clean) or [`bypass-paywalls-firefox-clean`](https://github.com/magnolia1234/bypass-paywalls-firefox-clean).

@prodan1234 do you mind continued testing and letting me know if this is breaking anything for you with just your filter list subscriptions?


Some example tested links that this should remove various footer bars / login prompts and scroll jacking/overlays from: 
1. `https://www.nytimes.com/2020/03/26/world/asia/afghanistan-iran-coronavirus.html`
2. `https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html`
3. `https://www.nytimes.com/2020/03/24/smarter-living/virus-remaking-space-while-homebound.html`
4. `https://www.nytimes.com/programs/productivity-challenge`
5. `https://www.nytimes.com/2020/03/23/smarter-living/why-mundane-moments-matter.html`

**Comment by prodan1234** [comment]
@yourduskquibbles all the links you included work well. Thanks for working on this!

**Comment by prodan1234** [comment]
Issue popped up again @yourduskquibbles 


### URL(s) where the issue occurs

`https://www.nytimes.com/2020/07/09/opinion/ban-cars-manhattan-cities.html`

### Describe the issue

The filter breaks the animations on the page. Disabling the filter fixes the issue. 

### Screenshot(s)

What article should look like:
![CleanShot 2020-07-09 at 22 48 23@2x](https://user-images.githubusercontent.com/29068702/87120926-84304580-c236-11ea-8c55-4a5d3c1a58e7.png)

What it looks like with the filter enabled. 
![CleanShot 2020-07-09 at 22 49 00@2x](https://user-images.githubusercontent.com/29068702/87120938-8a262680-c236-11ea-8545-7d31ae98806e.png)


### Versions

- Browser & Version: Chrome 83.0.4103.116
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin

**Comment by yourduskquibbles** [comment]
@prodan1234 This should be fixed now, please let me know if you are still seeing issues! `nytimes.com` has one of the craziest site designs to "fix" with their combination of CSS assets and naming so appreciate you flagging me. :)

**Comment by prodan1234** [comment]
@yourduskquibbles yep it works now. Thanks for the quick fix!
