### ISSUE TITLE
100 scrolling headers websites pack (1)

### ISSUE THREAD

**Issue by WowDude** [yourduskquibbles/webannoyances#25]
<details>
  <summary>Click to expand</summary>

.
**Websites:**
http://dih.pl/
http://gdeuslugi.ru/
http://globenergia.pl/
http://ksiazka.krakow.pl/
http://niezalezna.pl/
http://pro-beauty.pl/
http://przystanekplanszowka.pl/
http://telewizjarepublika.pl/
http://terazgostynin.pl/
http://twojahistoria.pl/
http://wideoproduktowe.pl/
http://www.chojnice.com/
http://www.detik.com/
http://www.empik.com/
http://www.espn.com/
http://www.excelsior.com.pl/
http://www.filmweb.pl/
http://www.gazeta.pl/
http://www.jd.com/
http://www.kasetony-reklamowe.com/
http://www.kuchniaupoli.pl/
http://www.lifedaily.com/
http://www.lodzkietargi.pl/
http://www.lokalnatelewizja.pl/
http://www.nicovideo.jp/
http://www.poczta-polska.pl/
http://www.poradnikzdrowie.pl/
http://www.rp.pl/
http://www.se.pl/
http://www.sina.com.cn/
http://www.swedish-princesses.pl/
http://www.terrarium.com.pl/
http://www.tvregionalna24.pl/
http://www.wikia.com/
http://www.wiocha.pl/
http://wyborcza.pl/
http://xinhuanet.com/
http://zegarkiipasja.pl/
https://allegro.pl/
https://bankowonline.pl/
https://businessinsider.com.pl/
https://coinmarketcap.com/
https://epremki.pl/
https://freshmail.pl/
https://home.pl/
https://jazdaprawna.pl/
https://jbzdy.pl/
https://kosmiczneujawnienie.com/
https://mailchimp.com/
https://mateuszskrzynski.wordpress.com/
https://mgotuje.pl/
https://naszemichalowo.wordpress.com/
https://niezlomni.com/
https://pikio.pl/
https://player.pl/
https://popvinyl.pl/
https://qdecor.pl/
https://rudaslaska.com.pl/
https://tvn24bis.pl/
https://us.blastingnews.com/
https://wordpress.com/
https://world.taobao.com/
https://www.1688.com/
https://www.auchandirect.pl/
https://www.blogger.com/
https://www.ceneo.pl/
https://www.dailymotion.com/
https://www.dkn.tv/
https://www.douyu.com/
https://www.dropbox.com/
https://www.elektroda.pl/
https://www.euro.com.pl/
https://www.gaia.com.pl/
https://www.gruparmf.pl/
https://www.harpersbazaar.pl/
https://www.hola.com/
https://www.idnes.cz/
https://www.indiatimes.com/
https://www.infoarchitekta.pl/
https://www.interia.pl/
https://www.kinopoisk.ru/
https://www.komputronik.pl/
https://www.maxelektro.pl/
https://www.mediaexpert.pl/
https://www.militaria.pl/
https://www.nowodworskiestates.pl/
https://www.o2.pl/
https://www.onet.pl/
https://www.otomoto.pl/
https://www.pixnet.net/
https://www.przelewy24.pl/
https://www.slideshare.net/
https://www.superpharm.pl/
https://www.tripadvisor.com/
https://www.turkiye.gov.tr/
https://www.tvn24.pl/
https://www.twitch.tv/
https://www.wikihow.com/
https://www.wykop.pl/
https://www.youm7.com/

**My settings:** 
Win 7 SP 1 [64bit]
FF 59.0.2 [64bit]
uBO 1.15.24
ND 13.48

**My filter lists:**
uBlock filters
uBlock filters – Unbreak​​​​​
uBlock filters – Annoyances​​​​​
Adguard Base Filters
EasyList
EasyPrivacy
Adguard Spyware Filters​​​​​
Fanboy’s Enhanced Tracking List​
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​
Fanboy’s Cookiemonster List​
I don't care about cookies
I'm OK with cookies​
Web Annoyances Ultralist​
and many more

</details>

**Comment by yourduskquibbles** [comment]
Thanks.

hola.com and twitch.tv don't work because they use the `!important` tag themselves and it ends up as a race condition that uBlock always loses. I need to open a uBlock Origin bug report about it but not sure there is anything that can be done.

**Comment by WowDude** [comment]
@yourduskquibbles 

Ok, I've checked them all (on the same my settings) and I confirm that 78 are fixed properly, however  20 (I've ommited the 2 you've mentioned about) still having issues:

6 left completely unfixed (still having whole sticky header, perhaps you just missed them?):
http://www.wikia.com/
https://rudaslaska.com.pl/
https://www.przelewy24.pl/
https://www.superpharm.pl/
https://www.twitch.tv/
https://www.dropbox.com/ <== in this one, also additionally, if you clear browser's cache & cookies, a glitch is appearing (the glitch is gone after reloading the website, and there is no glitch anymore until you clear the cache & cookies again):

<details>
  <summary>Click to expand</summary>

![dropbox](https://user-images.githubusercontent.com/37474031/38720739-b7c70dc6-3ef7-11e8-95c1-5b78d07fd192.png)

</details>
.

18 having noticeable issues:

this 1:
http://ksiazka.krakow.pl/pl/ <== in this one, with your filter `krakow.pl##.menu.clearfix:style(position: relative !important;)` the header is appearing and dissappearing while scrolling up/down, which is an annoyance, the proper filter is: `krakow.pl##.menu.clearfix:style(position: static !important; visibility: visible!important;)` which fixes the issue completely.

these 7 having an annoyance effect (more or less) - the header is sliding/parking out/in (like a car from/to a garage) while scrolling down/up, which is annoying:
http://www.espn.com/
http://pro-beauty.pl/
https://businessinsider.com.pl/
https://epremki.com/
https://www.euro.com.pl/
https://www.tripadvisor.com/
https://www.wikihow.com/

and the rest 10:
http://www.excelsior.com.pl/ <== the background header still left sticky while scrolling down:

<details>
  <summary>Click to expand</summary>

![capture_003_13042018_090058](https://user-images.githubusercontent.com/37474031/38721174-64723cb6-3ef9-11e8-97c2-2b4430d22836.png)

![capture_002_13042018_090042](https://user-images.githubusercontent.com/37474031/38721173-6442053c-3ef9-11e8-9461-de83a6f7ed28.png)

</details>
.

https://coinmarketcap.com/ <== the second header still sticky while scrolling (perhaps you've just missed it?):

<details>
  <summary>Click to expand</summary>

![capture_004_13042018_090503](https://user-images.githubusercontent.com/37474031/38721284-db87046c-3ef9-11e8-847d-0d0756d90869.png)

</details>
.

https://www.interia.pl/ <== right part of the header still sticky while scrolling:

<details>
  <summary>Click to expand</summary>

![capture_005_13042018_091037](https://user-images.githubusercontent.com/37474031/38721503-c4f3baf0-3efa-11e8-9afd-739b32ee9102.png)

</details>
.

https://www.militaria.pl/ <== some empty white container appearing/dissappearing while scrolling down/up:

<details>
  <summary>Click to expand</summary>

Before
![capture_006_13042018_091301](https://user-images.githubusercontent.com/37474031/38721563-08fc0b58-3efb-11e8-98c1-11b908c0e3aa.png)

After
![capture_007_13042018_091306](https://user-images.githubusercontent.com/37474031/38721565-0928a3c0-3efb-11e8-92b1-7f3d04e6c009.png)


</details>
.

https://www.onet.pl/ <== an annoying  animation in the header while scrolling slowly down/up

https://www.tvn24.pl/ <== the header is filckering (quickly appearing/dissappearing) while scrolling down/up (especially noticeable while scrolling not too fast), on the screenshoot you can see that it's currenlty in the dissappear state:

<details>
  <summary>Click to expand</summary>

Before
![capture_008_13042018_091755](https://user-images.githubusercontent.com/37474031/38721814-e4d9cffc-3efb-11e8-95c1-dd9798cedee3.png)

After
![capture_009_13042018_091757](https://user-images.githubusercontent.com/37474031/38721817-e641cdb8-3efb-11e8-8f87-c8e8da613dcd.png)

</details>
.

https://www.o2.pl/ <== not sure about this one, are the sticky widgets worth fixing them or just leave the website as is, as they seems like having some functionality and being just a kind of website desing?

**Comment by yourduskquibbles** [comment]
Thanks I will further check these. I think some of them may be showing up based on region IP filters being applied by the website, I don't have access to a Polish IP address but will try to track something down.

**Comment by yourduskquibbles** [comment]
Also to note, some of the sliding up/down issues you are describing is based on the site javascript loading entirely new DIV names when there is page action such as scrolling up/down. If you right click and inspect element you can see this action in the debug panel. 

From what I have found sometimes it can be mitigated with additional CSS overrides of `transition` and `transform`, or changing `margin` or `padding` settings but sometimes I can't find a perfect solution for "flashing" problem you describe.

**Comment by yourduskquibbles** [comment]
One other thing that may be causing issues on your side that I will test for is screen resolution. Some times there are multiple solutions needed based on screen width used. I was testing on a wide monitor yesterday, will need to change the browser size to see if some of what you are describing is caused by narrower width.

**Comment by WowDude** [comment]
> @yourduskquibbles : Also to note, some of the sliding up/down issues you are describing is based on the site javascript loading entirely new DIV names when there is page action such as scrolling up/down. If you right click and inspect element you can see this action in the debug panel.
> 
> From what I have found sometimes it can be mitigated with additional CSS overrides of transition and transform, or changing margin or padding settings but sometimes I can't find a perfect solution for "flashing" problem you describe.

I know,, in this case if it's to hard or impossible to fix, they can be just left as is, it'll be fine.

> @yourduskquibbles : One other thing that may be causing issues on your side that I will test for is screen resolution. Some times there are multiple solutions needed based on screen width used. I was testing on a wide monitor yesterday, will need to change the browser size to see if some of what you are describing is caused by narrower width.

I know, not first time I encoutered it, my res is 1280x1024 + DPI 125%, and sometimes this creates differencies for different people like here: https://github.com/MajkiIT/polish-ads-filter/issues/6840
or here: https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/639.

> @yourduskquibbles : will need to change the browser size 

You might also try set the resolution via Responsive Mode tool from Inspector tools in a browser:
https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by yourduskquibbles** [comment]
@WowDude please test the updates. I used a browser size of 1280px ([using a browser resize plugin](https://chrome.google.com/webstore/detail/browser-resize/pnmdcoaajafdppfpioijldebfbpogopn)) to create these updates so hopefully seeing what you are seeing.

**Comment by WowDude** [comment]
> @yourduskquibbles :
> @WowDude please test the updates.

I've tested the updates right now, 7 issues out of 20 has been fixed, I've edited my previous https://github.com/yourduskquibbles/webannoyances/issues/25#issuecomment-381049181 to highlight the fixed urls.

> @yourduskquibbles : 
I used a browser size of 1280px (using a browser resize plugin) to create these updates so hopefully seeing what you are seeing.

Is there any difference between 
these tools:
https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode
https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports
vs these tools:
https://chrome.google.com/webstore/detail/browser-resize/pnmdcoaajafdppfpioijldebfbpogopn
?

**Comment by yourduskquibbles** [comment]
excelsior.pl from what I can tell that header space is part of the websites background so unable to shift that up. Will investigate the others, I thought all had been fixed from my end.

**Comment by WowDude** [comment]
As for:
https://www.dropbox.com/ is fixed

https://www.superpharm.pl/ is fixed only partially coz still has the slide annoyance effect, must add this filter too: `superpharm.pl##.page-wrapper:style(padding-top: 0px !important;)` this fixes it completely.

As for:
https://rudaslaska.com.pl/ still the issue persists on all browsers, different browsers window sizes, even with Windows DPI set back at 100%

http://www.wikia.com/ still the issue persists, additional hints: 
- when I go to the website it loads as http://www.wikia.com/explore-pl
- the issue occurs only if browser's width is at least 1295 or more

You can also try via polish proxy as well, for example: `147.135.210.114:54566`

**Comment by yourduskquibbles** [comment]
Thanks for update wikia link, that finally worked and was able to load the global header. For rudalaska.com.pl are you sure you don't have cosmetic filters disabled? I tried with proxy and still see no issue that isn't solved by my previously added filters. I will add the update for superpharm.pl and wikia now.

**Comment by KonoromiHimaries** [comment]
@yourduskquibbles look here https://github.com/KonoromiHimaries/polish-ads-filter/blob/master/internal-filters/headers/adblock_headery.txt

**Comment by WowDude** [comment]
@KonoromiHimaries you mean import from:
https://github.com/KonoromiHimaries/polish-ads-filter/blob/master/internal-filters/headers/ to 
https://github.com/yourduskquibbles/webannoyances or vice cersa?

**Comment by yourduskquibbles** [comment]
@WowDude @KonoromiHimaries If there is a dedicated Polish filter maintainer, I think it makes the most sense to have all the `*.pl` header filters kept on that list. I will paste all `*.pl` filters I have added into Web Annoyances Ultralist in the next post.

**Comment by WowDude** [comment]
@yourduskquibbles ok, just don't forget one thing, despite the fact that most of PL header filters added to your lists are `.pl` domains, some of PL header filters are `.com` / `.info` / `.org` domains...

**Comment by yourduskquibbles** [comment]
@KonoromiHimaries -- Proposed filters to move to Polish list are listed below, I can leave `.com` / `.info` / `.org` domains in my list.

`allegro.pl##.opbox-metrum-header--default:style(position: relative !important;)`
`auchandirect.pl##.header:style(position: absolute !important;)`
`auchandirect.pl##.user-options:style(position: absolute !important;)`
`bankowonline.pl###menu:style(position: absolute !important;)`
`businessinsider.com.pl###dlbi-header:style(position: absolute !important;)`
`ceneo.pl##.header-container:style(position: relative !important;)`
`dih.pl##.on.fixedNav:style(position: absolute !important;)`
`elektroda.pl##.button_open`
`elektroda.pl##.hidden-print.topbar-wrap:style(position: absolute !important;)`
`euro.com.pl###top:style(position: relative !important;)`
`excelsior.com.pl##.navbar-fixed-top.navbar-inverse.navbar-default.main.navbar:style(position: absolute !important;)`
`filmweb.pl###mainPageHeader:style(position: absolute !important; transition: none !important;)`
`freshmail.pl##.fixed.bg-dark.main-menu-container:style(position: absolute !important;)`
`gaia.com.pl###topBar:style(position: absolute !important;)`
`gaia.com.pl##.fixed.top-menu:style(position: absolute !important;)`
`gaia.com.pl##.slideInDown.animated.sm-webpush`
`gazeta.pl##.hat_dark.mod_hat.page_top > .container-fluid:style(position: absolute !important;)`
`gazeta.pl##.hpFeed.mod_hat2014.mod:style(position: relative !important; top: 0 !important;)`
`globenergia.pl##.fadeInDown.object-visible.animated.clearfix.fixed.header:style(position: absolute !important;)`
`gruparmf.pl##.visible.chaser`
`harpersbazaar.pl##.fixed-active.main-nav-box:style(position: absolute !important;)`
`home.pl###nav_top:style(position: relative !important;)`
`infoarchitekta.pl###ciasteczka`
`infoarchitekta.pl##.szer_body.nav_belka_dwa:style(position: relative !important;)`
`interia.pl###inpl_cp_cnt`
`interia.pl##.account:style(position: absolute !important;)`
`interia.pl##.header-bar:style(position: absolute !important;)`
`jbzdy.pl###top:style(position: absolute !important;)`
`komputronik.pl##.header-wrap:style(position: relative !important;)`
`komputronik.pl##ktr-cookie-law`
`komputronik.pl##ktr-rollup`
`krakow.pl##.eventOrganizer`
`krakow.pl##.language-picker:style(position: absolute !important;)`
`krakow.pl##.menu.clearfix:style(position: static !important; visibility: visible!important;)`
`kuchniaupoli.pl##.navbar-fixed-top.navbar-custom.navbar:style(position: absolute !important;)`
`linuxportal.pl###naglowek:style(position: absolute !important;)`
`linuxportal.pl###przeczytaj_link_nast_2`
`linuxportal.pl###przeczytaj_link_pop_2`
`linuxportal.pl##body > div:nth-of-type(5)`
`lodzkietargi.pl###popup_mlm`
`lodzkietargi.pl###reklama-mini-outer`
`lodzkietargi.pl##.header-menu:style(position: absolute !important;)`
`lokalnatelewizja.pl###main_nav:style(position: relative !important;)`
`luksusowemieszkania.pl##.fixed.ng-search-bar`
`maxelektro.pl##.headhesive--stick.headhesive.container.header-page`
`mediaexpert.pl###ban_left > .bann > .js-proGA`
`mediaexpert.pl###ban_right > .bann > .js-proGA`
`mediaexpert.pl###miniBasket:style(position: static !important;)`
`mediaexpert.pl##.js-primeBarSticky.m-primeBar:style(position: static !important;)`
`mediaexpert.pl##.m-search.search_form:style(position: static !important;)`
`mgotuje.pl###navigation:style(position: relative !important;)`
`militaria.pl###layout-wrapper:before:style(height: 0px !important;)`
`militaria.pl##.header:style(position: static !important;)`
`mtb-xc.pl###main-menu:style(position: relative !important;)`
`mtb-xc.pl###sidebar:style(position: relative !important;)`
`mtb-xc.pl###social_counter-0`
`mtb-xc.pl##.sticky-inside-pad:style(height: 0px !important;)`
`niezalezna.pl###header:style(position: relative !important;)`
`nowodworskiestates.pl##.shadow.swim-menu:style(position: absolute !important;)`
`o2.pl##._1RBj1.Jkoz5:style(position: absolute !important;)`
`o2.pl##._2yC7E.bu4XW:style(position: absolute !important;)`
`o2.pl##._3g4kZ._3TieQ:style(position: absolute !important;)`
`o2.pl##body:style(overflow-x: hidden !important; overflow-y: auto !important;)`
`onet.pl##.notificationPrompt`
`onet.pl##.pageHeader *:style(transition: none !important;)`
`onet.pl##.pageHeader.switch`
`onet.pl##.pageHeader:style(position: absolute !important; transition: none !important;)`
`otomoto.pl##.header-container:style(position: absolute !important;)`
`otomoto.pl##.social-float-bar`
`pikio.pl##.td-affix.td-header-main-menu.td-header-row:style(position: absolute !important;)`
`player.pl##.navbar-wrapper:style(position: absolute !important;)`
`poczta-polska.pl##.topper:style(position: absolute !important;)`
`popvinyl.pl##.navbar-fixed-top.navbar-default.navbar:style(position: absolute !important;)`
`poradnikzdrowie.pl##.fixed.font_lower.menubar:style(position: absolute !important;)`
`pro-beauty.pl###ui-to-top`
`pro-beauty.pl##.flex-nowrap-lg.flex-wrap-sm.range-xs-center.reveal-sm-flex:style(position: relative !important;)`
`pro-beauty.pl##.rd-navbar--is-stuck.rd-navbar-static.rd-navbar-light.rd-navbar-minimal.rd-navbar:style(position: absolute !important;)`
`przelewy24.pl###menucontainerfloat`
`przelewy24.pl###side-menu-contener:style(position: absolute !important;)`
`przelewy24.pl##.menu-rwd.navbar-fixed-top.navbar-default.navbar:style(position: absolute !important;)`
`przystanekplanszowka.pl##.td-affix.td-header-gradient.td-header-menu-wrap:style(position: absolute !important;)`
`qdecor.pl##.menuLista:style(margin-top: 0px !important;)`
`qdecor.pl##.nav-down:style(position: relative !important; top: 0px !important;)`
`qdecor.pl##.nav-up:style(position: relative !important; top: 0px !important;)`
`r5.com.pl##.grid.page.navbar.menu.secondary.padded.fixed.ui:style(position: absolute !important;)`
`rp.pl##.linear-tv__iframe:style(position: static !important;)`
`rp.pl##.mk-subscription`
`rp.pl##.site-header__wrapper:style(position: relative !important;)`
`rudaslaska.com.pl###cookies-message`
`se.pl###mpc_cookie_intro`
`se.pl###social-widget`
`se.pl##.menu:style(position: relative !important;)`
`smartage.pl##.theiaStickySidebar:style(position: static !important;)`
`stopnadwadze.pl###bottom-bar:style(position: absolute !important;)`
`stopnadwadze.pl##.theiaStickySidebar:style(position: static !important;)`
`stopnadwadze.pl##body:style(overflow-x: hidden !important; overflow-y: auto !important;)`
`superpharm.pl###intercom-container`
`superpharm.pl###pushAdUpBanner`
`superpharm.pl##.page-header:style(position: static !important; top: 0px !important;)`
`superpharm.pl##.page-wrapper:style(padding-top: 0px !important;)`
`swedish-princesses.pl###LinkList60:style(position: relative !important;)`
`telewizjarepublika.pl###header-top:style(position: absolute !important;)`
`terazgostynin.pl##.header-scroll.mainMenu.belka_slide`
`terrarium.com.pl###secondary-bar:style(position: absolute !important;)`
`tvn24.pl###GemiusXYMap\:nav:style(position: absolute !important; top: 128px !important;)`
`tvn24.pl###msgLayer`
`tvn24.pl##.headerTop:style(position: absolute !important;)`
`tvn24.pl##body:style(overflow-x: hidden !important; overflow-y: auto !important;)`
`tvn24bis.pl###navigation-main:style(position: relative !important;)`
`tvn24bis.pl##.header-network:style(position: absolute !important;)`
`tvregionalna24.pl###main_nav:style(position: relative !important;)`
`tvregionalna24.pl###offbox-sidebar:style(position: relative !important;)`
`tvregionalna24.pl##.affix.offbox-widget:style(position: absolute !important;)`
`twojahistoria.pl###alt-header`
`wideoproduktowe.pl###nav-topbar:style(position: absolute !important; transition: none !important;)`
`wiocha.pl##.headerband:style(position: absolute !important;)`
`wyborcza.pl###wyborczaHat:style(position: absolute !important;)`
`wykop.pl###nav:style(position: absolute !important;)`
`zegarkiipasja.pl###header:style(position: absolute !important;)`
`zegarkiipasja.pl##.hidden-xs.gl-autohide-stickyheader.gl-menu-w100:style(position: absolute !important;)`
`zegarkiipasja.pl##.ng-scope.emelu-lightbox-target`
`zegarkiipasja.pl##body:style(overflow-x: hidden !important; overflow-y: auto !important;)`
`businessinsider.com.pl###dlbi-header:style(position: absolute !important;)`

**Comment by WowDude** [comment]
> @yourduskquibbles : I can leave `.com` / `.info` / `.org` domains in my list.

If they are PL, why then?

**Comment by yourduskquibbles** [comment]
> @WowDude  If they are PL, why then?

Tell me which ones to move I am OK with that -- I just don't have the time to go hunting through my list to find them right now :)

**Comment by WowDude** [comment]
@yourduskquibbles : 

### 1
PL headers you added in the past are your concern (anyway if we find/hunt some PL headers we'll notice you), for now I can tell you what PL domains I reported to you last days:

From this issue:

```
http://www.chojnice.com/
http://www.empik.com/
http://www.kasetony-reklamowe.com/
http://www.wikia.com/
https://kosmiczneujawnienie.com/
```

From https://github.com/yourduskquibbles/webannoyances/issues/22:
http://radiopoznan.fm/

### 2
@KonoromiHimaries keep in mind that some of the PL headers could have their pair filters that can be  some general filters, without which, a standalone PL header filter can have issues and may not work correctly (but I guess most of them will work fine).
