### ISSUE TITLE
chocolatey.org

### ISSUE THREAD

**Issue by vavavr00m** [yourduskquibbles/webannoyances#257]
### URL(s) where the issue occurs

- https://chocolatey.org/

### Describe the issue

- Collapsing Right Sidebar

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4675132/97088694-40d2d900-1665-11eb-90bc-8126049f4cb8.png)

### Versions

- Browser & Version: Version 86.0.4240.111 (Official Build) (64-bit)
- Adblocker: uBlock Origin v1.30.6 & Adguard 7.5 nightly 33 (build 3407, CL 1.7.114)

### Settings

- Lots

### Notes

- This was what I picked up from the picker:

chocolatey.org##.collapsed.shadow.d-md-block.d-none.d-hash-none.py-3.btn-announcement-notifications.btn-collapsing-right-sidebar.btn-primary.btn

**Comment by yourduskquibbles** [comment]
Thanks for reporting @vavavr00m! This should be fixed now.

**Comment by vavavr00m** [comment]
@yourduskquibbles not fixed on my end - both AdGuard & uBlock Origin.

**Comment by yourduskquibbles** [comment]
Is the sidebar item not pinned in place for you now after updating Web Annoyances Ultalist?

The filter[1] I added should be loaded if you are subscribed to just `[ultralist.txt](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt)` through the `[floating_filters.txt](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/floating_filters.txt)` sublist that should get loaded and applied.

Filter you can test after validating Web Annoyances Ultralist is updated after purging cache and clicking update filters is

[1] `chocolatey.org##.collapsed.shadow.d-md-block.d-none.d-hash-none.py-3.btn-announcement-notifications.btn-collapsing-right-sidebar.btn-primary.btn:style(position: absolute !important;)`

**Comment by vavavr00m** [comment]
Oh I see what you mean. I didn't realize it was pinned. I was hoping it would be removed since it contains entries from the [events](https://chocolatey.org/events) page under Product.

**Comment by yourduskquibbles** [comment]
@vavavr00m I would prefer not to remove it entirely as I see it as a valid self-advertisement for the company. I think a filter to remove it entirely like that belongs in a personal list not a list used by lots of people since I see it as a valid part of the site that I don't want to remove functionality of.

To me, pinning the object in place removes the annoyance factor of it and still allows a user to click on it if they are interested in seeing more about the alerts.
