### ISSUE TITLE
gadsdentimes.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#347]
### URL(s) where the issue occurs

`https://www.gadsdentimes.com`

### Describe the issue

Subscription nag.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131928223-c9dc6e04-8572-43ca-8b55-f2b0ec38b7e9.png)

### Versions

- Browser & Version: Firefox 91.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks again!

**Comment by Mennaruuk** [comment]
Closing this issue, since this is one of many sites (>100) that have the same problem, don't wanna overwhelm you! If you're still curious, I found two filters that work, except scrolling gets disabled.

`gadsdentimes.com##.tp-modal`
`gadsdentimes.com##.tp-active.tp-backdrop`

**Comment by yourduskquibbles** [comment]
I am re-opening, i can't get the modal to popup though so don't know what I need to add to get the scroll bar back. Will keep testing and clicking around the site until i can get it to popup for me

**Comment by yourduskquibbles** [comment]
Nevermind, got it to load by disabling ubo entirely so now I can see what I need to add.

**Comment by yourduskquibbles** [comment]
I think this should solve the issue, didn't test on all the domains I'm adding for though, so hopefully the string of domains is still valid

**Comment by Mennaruuk** [comment]
THANK YOU SO MUCH FOR THIS BIG LIST! I don't know how you got it, but dang that's so many sites. I hope it was quick!

There's just one issue remaining: scrolling gets disabled on all sites I tested. Is there a way to allow scrolling?

![image](https://user-images.githubusercontent.com/52135169/132581786-134eec30-6eff-4858-b784-f09b5990ef5a.png)

**Comment by yourduskquibbles** [comment]
@Mennaruuk sorry I missed that was testing with another extension which was making it so I didn't catch this, I think this should be fixed now though with latest update. Please let me know!
